### ISSUE TITLE
User's can't create new posts or reply

### ISSUE THREAD

**Issue by fjbarrena** [vaadin/tori#302]
Working on:
     Liferay 6.2 EE

Creator of the site can post, reply, etc. but the rest of site members can't create or reply posts.

The new post button is not visible.

When a user enter in an existing post, the application shows the next message:

"Please log in to reply"

The error persists even when the user have administrator role

![image](https://cloud.githubusercontent.com/assets/1855013/4304631/20d3e3d2-3e72-11e4-9415-fe850b8705e7.png)

Permissions are right at Liferay level, because the user can create, reply, etc. posts at OOTB Liferay forum portlet, but not in Vaadin Forum Portlet.

**Comment by fmchugh** [comment]
I have logged in with my account on the Vaadin site and I still can't post to the forum.

**Comment by fmchugh** [comment]
Nevermind.  I always feel like this functionality should be on the first forum page.  I don't think to choose a forum to post to first.
