### ISSUE TITLE
deployment and running 

### ISSUE THREAD

**Issue by o-thentic** [vaadin/tori#304]
when i try to debug the default vaadin project after creating it this is what  i get
Directory: /welcome/

META-INF/ 	102 bytes 	Jan 19, 2015 12:39:52 PM
VAADIN/ 	102 bytes 	Jan 19, 2015 12:39:53 PM
WEB-INF/ 	102 bytes 	Jan 19, 2015 12:39:52 PM

i'm using google chrome and i entered http://localhost:8080/welcome
welcome is the name of my project.
I should be getting a button that says click me, but instead i get what is shown above. Any ideas?

**Comment by o-thentic** [comment]
Oh and i'm using eclipse...

**Comment by tomivirkki** [comment]
This is not a Tori issue. Please post your Vaadin related questions on our forum at vaadin.com/forum
