### ISSUE TITLE
javadocs for Labels.setEnabled is wrong

### ISSUE THREAD

**Issue by rogerhart2** [vaadin/tori#305]
I'm using Vaadin charts 2.0.0.  The javadocs for the com.vaadin.addon.charts.model.Labels.setEnabled(Boolean) method says that the default setting is true. This is not the case.  The default setting is false. The no-arg class constructor needs to call this(false);

**Comment by Peppe-** [comment]
Note that this is the issue tracker for 'tori', the forum software. Bugs to Vaadin Charts and Vaadin itself should go to dev.vaadin.com
